GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5d3b139c49e0171d373b26ac

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "amazing person",
    "subscribedToChannel":"web dev simplified"
}

###

DELETE http://localhost:3000/subscribers/5d3b0f94a9df3d183f33210e

###

PATCH http://localhost:3000/subscribers/5d3b139c49e0171d373b26ac
Content-Type: application/json


{
    "name": "sam",
    "subscribedToChannel":"web dev simplified"
}


